stages:
    - test
    - prepare
    - build
    - compatibility
    - release


#-----------------------------------------



.common: &common
    tags:
        - shell
    interruptible: true

.make_app: &make_app
    rules:
        -   changes:
                - front/**/*
                - back/**/*
            when: on_success
    before_script:
        - export TAG=$(date '+%Y.%m.%d')
        - printenv
        - >
            if [ $(uname) == "Darwin" ]; then
            	sed -i '' "s/PACKAGE_VERSION/${TAG}/g" ./back/package.json
            	sed -i '' "s/PACKAGE_VERSION/${TAG}/g" front/package.json
            else
            	sed -i "s/PACKAGE_VERSION/${TAG}/g" back/package.json
            	sed -i "s/PACKAGE_VERSION/${TAG}/g" front/package.json
            fi


#-----------------------------------------


eslint:
    stage: test
    interruptible: true
    image: registry.gitlab.com/pipeline-components/eslint:0.72.0
    script:
        - (cd back && eslint --color .)
        - (cd compatibility && eslint --color .)


#-----------------------------------------


prepare:
    <<: *common
    <<: *make_app
    stage: prepare
    image: node:alpine
    script:
        - cd front
        - pnpm install --prod --frozen-lockfile
        - pnpm run build
        - ./changelog.js ./dist/webdb/changelog.html
    artifacts:
        paths:
            - ./front/dist/webdb/

clean:
    <<: *common
    stage: prepare
    image: node:alpine
    script:
        - docker container prune -f
        - docker volume prune --all -f
        - docker system prune --all --volumes -f


#-----------------------------------------


build:
    <<: *common
    <<: *make_app
    dependencies:
        - prepare
    stage: build
    image: docker:latest
    variables:
        IMAGE_NAME: webdb/app
    script:
        - cp -fr ./front/dist/webdb/* ./back/static/
        - cd back
        - docker login -u 'aleluff' -p $DOCKER_PASS
        - docker buildx create --use
        - docker buildx build --cache-from $IMAGE_NAME:$CI_COMMIT_REF_NAME --platform linux/arm64,linux/amd64 --sbom=true --provenance=true -t $IMAGE_NAME:$CI_PIPELINE_ID --push .
        - docker rm -f $(docker ps -a -q --filter ancestor=moby/buildkit:buildx-stable-1)


#-----------------------------------------


compatibility:
    <<: *common
    stage: compatibility
    image: docker:latest
    rules:
        -   if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"
            when: on_success
    script:
        - cd compatibility
        - npm install --prod --frozen-lockfile
        - npm run test:app
        - npm run test:docker || echo
        - npm run fail:junit
    artifacts:
        expire_in: never
        paths:
            - ./compatibility/report.xml


#-----------------------------------------


release:
    <<: *common
    dependencies:
        - compatibility
    stage: release
    image: docker:latest
    variables:
        IMAGE_NAME: webdb/app
    script:
        - docker login -u 'aleluff' -p $DOCKER_PASS
        - docker tag $IMAGE_NAME:$CI_COMMIT_REF_NAME $IMAGE_NAME:$CI_PIPELINE_ID
        - >
            if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
                docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:$CI_PIPELINE_ID
                docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CI_PIPELINE_ID
            fi
        - docker push $IMAGE_NAME:$CI_PIPELINE_ID
